### ISSUE TITLE
Implement pom.xml definitions for compliance with OSSRH

### ISSUE THREAD

**Issue by lewismc** [Unidata/jj2000#2]
As part of consuming Unidata artifacts within the Apache [Tika project](http://tika.apache.org), I've been working for some time to monitor the Unidata lists and shadow releases with aritfact publication to Maven central as per https://wiki.apache.org/tika/ThirdPartySonaType

Recently, when attempting to push the jj2000 artifact, I've found that OSSRH rejects the staging artifact due to a number of issue
 * pom validation: project name mising, URL missing, License Information missing, SCM URL missing and Developer Information missing
 * No sources.jar to accompany main jar
 * no javadoc.jar artifact to accompany main jar

**Comment by lewismc** [comment]
@dopplershift can you please suggest a forum of mailing list where I can discuss 3rd party dependencies present within the Unidata software artifacts?

**Comment by dopplershift** [comment]
Do you have a particular project in mind? Like netcdf-java?

**Comment by dopplershift** [comment]
Ok, now that I've looked over the Tika project, I'd say for netcdf-java:
- the public project list: netcdf-java@unidata.ucar.edu
- private support ticket list: support-netcdf-java@unidata.ucar.edu
- github issues: http://github.com/Unidata/thredds/issues

**Comment by lewismc** [comment]
Well...
I have an issue with one of the dependencies contained within your
repository, namely this one
https://artifacts.unidata.ucar.edu/content/repositories/unidata-3rdparty/org/itadaki/bzip2/
It was not on Maven central until I published it 2 days ago.
It is no longer maintained in it's current repository, but one or more of
the UCAR dependencies depend upon it.
I submitted a patch which is not being merged because the library is
unmaintained.

https://code.google.com/p/jbzip2/issues/detail?id=3

I was wondering what the workflow uis for migrating away from these
projects. I was maybe thinking about forking the code base and maintaining
it myself.


On Thu, Apr 23, 2015 at 2:17 PM, Ryan May <notifications@github.com> wrote:

> Ok, now that I've looked over the Tika project, I'd say for netcdf-java:
>
>    - the public project list: netcdf-java@unidata.ucar.edu
>    - private support ticket list: support-netcdf-java@unidata.ucar.edu
>    - github issues: http://github.com/Unidata/thredds/issues
>    <https://github.com/Unidata/thredds/issues>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unidata/jj2000/issues/2#issuecomment-95721469>.
>



-- 
*Lewis*

**Comment by dopplershift** [comment]
Let's punt over to the github issues tracker for the thredds repo (which holds netcdf-java).

**Comment by lewismc** [comment]
ACK

**Comment by lewismc** [comment]
Where is it? Can you please reference?

**Comment by dopplershift** [comment]
https://github.com/Unidata/thredds/issues
