### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by puntogil** [Unidata/jj2000#5]
Hi,
We try to import your customized release...
there is a bit of confusion regarding the license of this library
in  https://code.google.com/p/jj2000/ is reported as LGPLv2
in the pom file is used jj2000 License (master).
For Fedora we have a problem for import this library.
For two reasons, jj2000 :
1. The license it is under is non-free (only "JJ2000 Partners" have
right to use, there is no right to modify, heavy use restrictions based
on standard compliance).
2. JPEG 2000 is heavily patent mined.
For use non free code if such usage restriction makes the license incompatible with The Open Source Definition and The Free Software Definition. Because thredds/grib library distribution includes this software, it effectively becomes proprietary software itself.
thanks in advance
regards

**Comment by JohnLCaron** [comment]
Not much we can do about jj2000. The grib module, which uses jj2000, is optional for netcdf-java library. You can leave it out if you need to. Let us know if you need us to to do something for that.

**Comment by puntogil** [comment]
thanks for your help
for now removed jj2000 support in grib sub module
regards
