### ISSUE TITLE
Publish 5.3 to Maven Central

### ISSUE THREAD

**Issue by mattcg** [Unidata/jj2000#6]
Thank you for your work on this. Would it be possible to publish 5.3 to Maven Central? You already have 5.2 there.

That would allow this code to be used in [jai-imageio/jai-imageio-jpeg2000](https://github.com/jai-imageio/jai-imageio-jpeg2000).

**Comment by tballison** [comment]
We'd like to get this into Apache Tika for the 1.16 release fairly soon.  If you're willing, I can fork and publish to maven central with a group id=org.tallison.  Or, if you'd be willing to publish it yourselves, that'd be great.  Thank you!

**Comment by mattcg** [comment]
Reverse reference: [TIKA-2399](https://issues.apache.org/jira/browse/).

**Comment by Lonzak** [comment]
+1 vote (to release not only 5.3 but also 5.4 to maven central)

**Comment by dopplershift** [comment]
We (Unidata) actually do not upload any of our artifacts to Maven Central (someone else uploaded the 5.2 build). We only upload to [our own artifacts server](https://artifacts.unidata.ucar.edu/#browse/browse:unidata-releases).

Happy to have anyone else upload to Maven Central for their needs. We don't claim to own this code, we're just hosting the repo and making sure it works for [netcdf-java](https://github.com/Unidata/netcdf-java).
