### ISSUE TITLE
Sample bit depth limit of 8 bits

### ISSUE THREAD

**Issue by jstumpe** [Unidata/jj2000#7]
While testing with several JPEG2000 streams, it turned out that jj2000 5.1 isn't supporting images that have an original component bit depth greater than 8.

But as there are many JPEG2000 streams with more than 8 bits component bit depth, I would like to know if there is a possibility to overcome this jj2000 limit of 8 bits.

Is there a newer jj2000 version around, or a patch that removes this limitation?

Any hint is welcome.

Thanks

**Comment by dopplershift** [comment]
Maybe there's something useful here: https://github.com/jai-imageio/jai-imageio-jpeg2000

Otherwise, I don't have anything else to offer, sorry.

**Comment by jstumpe** [comment]
Thanks
