### ISSUE TITLE
License is unclear

### ISSUE THREAD

**Issue by dkonemann** [Unidata/jj2000#9]
Hi,
1. This fork has a different license than https://code.google.com/archive/p/jj2000 notices (LGPL).
2. Next to this in case LGPL is correct, I cannot find which version.

Can you clarify this?

Thanks,
Dietmar

**Comment by dkonemann** [comment]
On https://mvnrepository.com/artifact/edu.ucar/jj2000 it says it is Apache 2.0

**Comment by dopplershift** [comment]
So this is the license/copyright information from the original code:
https://github.com/Unidata/jj2000/blob/master/COPYRIGHT

This is definitely not Apache 2.0 or LGPL. Beyond that, I cannot really clarify the license, as we're not the copyright holders on this code. We are merely hosting code that was originally published elsewhere. The copy on google code has an issue [questioning the listing as LGPL](https://code.google.com/archive/p/jj2000/issues/3), so I'm not particularly confident that there has ever been a relicensing. (The listing on mvnrepository.com is not controlled by us, but I'd say it's also inaccurate.)
